config/routes.rb
CroquetClub::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "core#index"

  get "core" => "core#booking_monitor"
  
  match "/about_the_club" => "core#about_the_club", via: :get
  match "/how_to_join" => "core#how_to_join", via: :get
  match "/what_you_need" => "core#what_you_need", via: :get
  match "/programme" => "core#programme", via: :get
  match "/news_letters" => "core#news_letters", via: :get
  match "/club_matters" => "core#club_matters", via: :get
  match "/how_to_get_there" => "core#how_to_get_there", via: :get
  match "/book_a_lawn" => "core#book_a_lawn", via: :get
  match "/links" => "core#links", via: :get

  match "/update_booking" => "core#update_booking", via: :post

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/booking.rb
class Booking < ActiveRecord::Base
    validates_presence_of :lawn_id, :time, :date
    belongs_to :lawn
end

app/models/event.rb
class Event < ActiveRecord::Base
    validates_presence_of :title, :date, :description
end

app/models/lawn.rb
class Lawn < ActiveRecord::Base
    validates_presence_of :description
    has_many :bookings, :dependent => :destroy

    def to_s
        description
    end
end

app/models/news_letter.rb
class NewsLetter < ActiveRecord::Base
	mount_uploader :pdf, PdfUploader
    validates_presence_of :title, :date, :pdf
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/core_controller.rb
require 'messenger/sse'

class CoreController < ApplicationController
  include ActionController::Live

  def index
    @title = "Home"
  end

  def about_the_club
    @title = "About the Club"
  end

  def how_to_join
    @title = "How to Join"
  end

  def what_you_need
    @title = "What You Need"
  end

  def programme
    @title = "#{Time.now.year} Programme"
    @events = Event.where("date >= ?", Time.now).order(date: :asc).all
    @past_events = Event.where("date < ?", Time.now).order(date: :desc).all
  end

  def news_letters
    @title = "News Letters"
    @letters = NewsLetter.order(date: :desc).all
    @grouped = @letters.group_by {|y| y.date.year }
  end

  def club_matters
    @title = "Club Matters"
  end

  def how_to_get_there
    @title = "How to get There"
  end

  def book_a_lawn
    @title = "Book a Lawn"
    @bookings = Booking.all.group_by { |b| b.lawn_id }
  end

  def update_booking
    @booking = Booking.find(params[:booking_id])
    @booking.booked = true
    @booking.save
    $last_updated = @booking.id
    @lawn = Lawn.find(@booking.lawn_id)
  end

  def booking_monitor
    response.headers['Content-Type'] = "text/event-stream"

    sse = Messenger::SSE.new(response.stream)
    booking = Booking.find($last_updated)
    begin
      sse.write({ :booking_id => booking.id, :booked => booking.booked}, :event => 'update')
    rescue
      #When client disconnects get IOError
    ensure
      sse.close
    end
  end

  def links
    @title = "Links to Croquet Sites"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title
		base_title = "Cheam Croquet & Bowls Club"

		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
end

app/helpers/core_helper.rb
module CoreHelper
end

app/views/core/_event.html.erb
<section>
    <h3><%= event.title %> (<%= event.date.to_formatted_s(:long) %>)</h3>
    <p>
        <%= event.description %>
    </p>
</section>

app/views/core/about_the_club.html.erb
<h1>About the Club</h1>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquam purus metus, ut dictum purus auctor eu. Morbi sagittis lorem a tristique mollis. Cras in dapibus risus, id fermentum sem. Phasellus dapibus neque vitae congue ullamcorper. Nullam porttitor interdum quam eget feugiat. Cras interdum metus ac lectus iaculis, at tincidunt augue molestie. Nunc at tellus nibh. Vivamus dui nibh, auctor sed nunc in, tempus accumsan lectus. Sed sed mi urna. In dignissim dictum ultricies. Maecenas facilisis sem et facilisis mattis. Maecenas in ullamcorper tortor. Suspendisse sollicitudin pellentesque sapien sit amet venenatis. Sed vitae interdum orci. Phasellus felis ipsum, semper ac lorem a, porttitor pulvinar nisl. Curabitur eu sagittis odio.</p>

<p>Aliquam erat volutpat. Nullam ultrices elit eget mi ultrices feugiat. Fusce vel elit non nulla tempus bibendum non nec sapien. Suspendisse tincidunt nisl condimentum, posuere diam et, laoreet nulla. Ut odio ante, placerat quis lectus sit amet, venenatis tincidunt ipsum. Integer est diam, rutrum eget ante nec, ultricies tempor enim. Nullam lobortis est nunc, non faucibus nulla consectetur at.</p>

<p>Integer suscipit massa vel luctus ornare. Suspendisse varius aliquet elit, in auctor nibh rutrum et. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla eu mauris non sem dapibus malesuada. Donec nec cursus mauris, vel feugiat ligula. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec leo dolor, ultricies vitae ligula non, lobortis consequat elit. Donec varius dapibus aliquet. Pellentesque a purus sodales, adipiscing justo laoreet, fringilla est. Mauris mi felis, consequat id diam vel, fringilla condimentum eros. Quisque eget hendrerit mi, ut facilisis odio. Aenean lacus odio, tempor nec hendrerit non, pellentesque non lorem. Vestibulum laoreet neque at nunc scelerisque, ut lobortis nunc rutrum. Aliquam sed tortor eu lacus pulvinar faucibus semper eget lacus. Nullam vitae lobortis diam. Aenean scelerisque euismod scelerisque.</p>

<p>Mauris a porta orci. In placerat odio diam, id porta felis pretium feugiat. Pellentesque a tortor vel dui suscipit interdum. Integer rhoncus id nisi sed interdum. Nunc tincidunt purus vel rutrum sodales. Praesent eu purus egestas, consectetur lacus eu, porta sapien. Nam dapibus magna vel mi interdum, nec molestie eros elementum. Proin dictum odio eu pretium dapibus. Proin bibendum pellentesque eros non auctor.</p>

<p>Nulla eu ligula ac arcu pellentesque tempus. Integer lacinia mauris at egestas auctor. Aliquam lobortis elementum eros, eu vulputate felis gravida vitae. Vestibulum ornare ut orci at aliquet. Duis condimentum luctus augue, ut vulputate libero suscipit vel. Sed consequat dui ut luctus vulputate. Suspendisse eget lectus nec risus malesuada malesuada in quis nulla. Proin nec facilisis nunc.</p>

app/views/core/book_a_lawn.html.erb
<h1>Book a Lawn</h1>

<p>Book a lawn at the club.</p>

<p>All bookings are for two hours.</p>

<% @bookings.each do |lawn, booking| %>
    <section>
        <h3>Lawn: <%= lawn %></h3>
        <% booking.each do |b| %>
            <article id="<%= b.id %>">
                <p><%= b.date.to_formatted_s(:long) %> at <%= b.time.to_formatted_s(:time) %></p>
                <p class="booked"><%= b.booked ? "Not Available" : "Available" %></p>
                <%= button_to "Book this Slot", update_booking_path(booking_id: b), :disabled => b.booked? %>
            </article>
        <% end %>
        <br>
    </section>
<% end %>

app/views/core/club_matters.html.erb
<h1>Club Matters</h1>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eleifend ipsum id justo tempus fermentum. Pellentesque bibendum tempor eros, quis volutpat purus suscipit id. Morbi consequat sagittis dignissim. Mauris molestie auctor sem ut porta. Integer at ante dictum, ultricies felis sit amet, interdum sapien. Suspendisse vulputate dolor a risus venenatis, vitae porttitor dolor iaculis. Proin metus nisl, ultricies vitae lacinia condimentum, gravida at purus. Cras elit elit, molestie vitae auctor non, consequat sit amet justo.</p>

<p>Quisque sit amet ullamcorper est. Suspendisse feugiat, nulla sit amet dictum eleifend, risus odio vulputate mauris, nec hendrerit nisl dolor non lectus. Cras eu eleifend diam. Fusce cursus turpis metus, quis aliquet ante convallis luctus. Ut vel mauris vestibulum, tristique risus eget, iaculis mauris. Morbi odio ligula, vestibulum ut nulla non, feugiat hendrerit nisl. Nam volutpat enim vel augue ornare sodales. Sed congue eget urna ac dictum. Curabitur fringilla fringilla dolor, et mollis lacus accumsan nec. Ut vel varius felis, nec consequat dui.</p>

<p>Morbi consequat dictum sem nec tristique. Mauris vel enim vitae augue vestibulum rhoncus sed et velit. Vivamus mi ipsum, auctor non ipsum ut, accumsan feugiat metus. Sed malesuada in magna ac euismod. Sed malesuada dignissim nibh in mollis. Phasellus ut nisl nulla. Ut viverra metus magna, ac congue dolor lobortis sit amet. Praesent at viverra mi, sit amet suscipit magna. Quisque eget sagittis ante. Donec felis lorem, imperdiet ac venenatis tristique, laoreet at urna. Fusce erat massa, blandit quis mauris ac, vulputate commodo urna. Donec eu lacus ullamcorper odio suscipit lacinia quis eget turpis. Phasellus sed consequat mauris. Praesent ante orci, semper ac adipiscing vel, ultrices a diam. Mauris consectetur porttitor elit id adipiscing.</p>

<p>Vestibulum rutrum nunc eu erat tempus, ac egestas nisl venenatis. Duis consectetur, metus a sodales varius, elit mi suscipit massa, et vehicula libero elit in quam. Morbi a dictum dolor, nec dapibus turpis. Nullam dapibus a sem ut elementum. Fusce vel tempus est. Pellentesque faucibus nec quam in egestas. Sed volutpat accumsan neque, non consectetur velit faucibus eget. Phasellus suscipit sagittis ante. Maecenas felis nibh, egestas et pulvinar ac, pharetra a lacus. Phasellus et blandit metus, volutpat fermentum sem. Aliquam elementum bibendum mollis. Donec rutrum sed erat a consequat. Sed scelerisque et ante vulputate lacinia. Aenean ultricies diam eu ipsum pharetra, et fringilla metus interdum. Pellentesque consequat, neque eu pellentesque sagittis, nisi libero accumsan nunc, in pellentesque risus sem et purus.</p>

<p>Phasellus metus risus, interdum sit amet dui et, dignissim laoreet justo. Nulla pulvinar porttitor lobortis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu tincidunt orci. Vivamus mi enim, accumsan a vehicula in, dapibus a nisi. Duis sit amet felis ut urna congue consequat. Nulla ullamcorper vel ipsum vitae commodo. Morbi dictum, risus vitae ultrices cursus, nibh leo sagittis mauris, ac lacinia sapien est at risus. Aliquam sit amet elit ligula. Maecenas at semper neque. Etiam vitae lorem at nisi luctus elementum viverra id ipsum. Vivamus eget massa ut sapien ultrices rutrum id vitae quam. Nam condimentum, ipsum vestibulum fringilla ultrices, orci erat consectetur est, vitae auctor quam nulla id ante. Suspendisse venenatis iaculis mollis. Vestibulum eu rhoncus ipsum.</p>

app/views/core/how_to_get_there.html.erb
<h1>How to get There</h1>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc eu augue commodo, scelerisque eros sed, posuere odio. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque sed risus sed erat faucibus dignissim. Nunc dolor ante, aliquam tincidunt est nec, posuere dapibus erat. Maecenas commodo vehicula lacus quis sodales. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed dui nisi. Suspendisse potenti. Donec massa urna, dignissim in interdum sed, ullamcorper non lorem. Fusce consectetur ante eget erat lobortis dapibus.</p>

<p>Sed tempor dui a nibh rutrum, eu laoreet ligula molestie. Mauris lorem tortor, rutrum at aliquet eget, fermentum non mi. Mauris imperdiet est vel tortor rutrum hendrerit. Fusce ac libero ac justo egestas volutpat. Nulla eleifend nisi et dui fringilla dignissim. Curabitur at augue elit. Duis convallis, eros nec lobortis dignissim, turpis diam ullamcorper nibh, ut porttitor lectus nunc hendrerit massa. Pellentesque convallis lacinia condimentum. Donec posuere rhoncus lacus, quis tristique nisi aliquam eget. Nunc sit amet convallis ligula. Nam dapibus tristique libero, ac bibendum diam laoreet vel. Duis nibh libero, malesuada sed libero et, lobortis venenatis massa. Vivamus elementum lacinia nisl a tempor. Pellentesque id velit volutpat, iaculis justo sit amet, tempor nibh. Aliquam mollis feugiat blandit. Aenean consectetur, massa nec euismod dignissim, mi leo euismod turpis, at vehicula felis nisl a nisi.</p>

<p>Sed sit amet eleifend metus. Vivamus nec suscipit mauris. Suspendisse purus dui, ornare ut mollis ut, pharetra id enim. Donec semper varius ipsum at interdum. Maecenas eleifend purus diam, vel vehicula lacus auctor et. Etiam mi erat, vestibulum vel tempor sit amet, varius nec elit. Integer risus neque, sollicitudin nec vulputate et, auctor quis arcu. Mauris massa ipsum, ullamcorper vitae dignissim eu, tristique sed eros. Suspendisse aliquet magna turpis, vel ultrices dui ultrices ut. Integer semper elit vel posuere bibendum. Mauris venenatis tellus odio, et dapibus lectus elementum aliquet.</p>

<p>Praesent tristique dui sit amet est adipiscing ultricies. Cras sodales mattis posuere. Ut ornare, tellus eget vehicula luctus, purus urna scelerisque tellus, ut fermentum velit nunc ut turpis. Maecenas vitae lectus id lacus gravida vehicula rutrum ut tellus. Vestibulum eu eleifend tortor. Ut quis magna varius, bibendum ipsum non, sagittis elit. Praesent vel congue sapien. Suspendisse ut mauris sollicitudin nunc dictum porttitor. Fusce facilisis vestibulum lobortis. In at justo in enim consequat pretium at et leo. Ut et est id felis placerat lacinia quis ac lacus. Integer ullamcorper eu mauris ut congue.</p>

<p>Ut id vulputate elit. Sed aliquam lorem a ultricies iaculis. Donec malesuada lorem at tempor accumsan. Quisque elementum nisl in lorem bibendum placerat. In et libero quis libero gravida aliquet. Integer scelerisque lectus quis felis sollicitudin commodo. Sed rhoncus sed mauris dictum vulputate.</p>

app/views/core/how_to_join.html.erb
<h1>How to Join</h1>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada scelerisque diam non commodo. Sed nec urna eu ante imperdiet sollicitudin. Nunc sed sapien nisi. Sed tincidunt tellus nec consequat congue. In hac habitasse platea dictumst. Nulla facilisis volutpat velit a aliquet. Pellentesque id egestas lorem. Morbi eros orci, luctus non metus sit amet, euismod tempor leo. Nullam vel mattis dolor. Pellentesque placerat vulputate orci, ac laoreet dolor ultrices et. Etiam porta lectus egestas laoreet feugiat. Morbi sed laoreet velit.</p>

<p>Suspendisse potenti. Nulla eget justo eget mi facilisis auctor quis accumsan nulla. Curabitur venenatis, sem et tristique pellentesque, metus turpis mattis quam, quis tincidunt lorem ligula et lacus. Cras ultrices metus vel erat dapibus, vel mattis metus elementum. Donec nec nisi risus. In tempor felis eu ligula pretium, a volutpat eros elementum. Nam purus metus, pulvinar in sodales sit amet, dictum a purus.</p>

<p>Sed ac velit feugiat, tempus libero scelerisque, tincidunt urna. Cras nec sapien lectus. Aliquam sit amet commodo sem. Praesent vehicula est eu quam tempor, ac semper justo sagittis. Mauris volutpat, neque quis consectetur adipiscing, dui eros pellentesque velit, at pharetra dui purus id dui. Suspendisse rhoncus cursus ligula, vitae viverra dolor sagittis laoreet. Nullam fringilla, mi nec consectetur imperdiet, ante lacus tempus quam, et faucibus arcu lectus non dui. Curabitur ultricies ipsum et urna consequat, sit amet faucibus lectus ultricies.</p>

<p>Sed ultrices pretium orci eu tincidunt. Nunc ut libero molestie, volutpat augue vitae, porttitor massa. Nullam quis porttitor quam. Sed dignissim dui eu lacus iaculis scelerisque. Pellentesque id enim tempus, elementum sapien accumsan, consequat erat. Vestibulum facilisis lacinia facilisis. Vestibulum adipiscing metus malesuada nulla placerat, a rutrum tellus volutpat. Nulla eget ornare erat. Etiam sit amet purus vitae risus commodo consectetur eu ut leo. Duis consectetur eros ligula, id aliquet dolor varius at.</p>

<p>Sed tincidunt urna lobortis felis malesuada, sed pretium odio posuere. Mauris venenatis ut enim a blandit. In vel iaculis ipsum. In tempor ultrices porta. Proin sagittis, est aliquam convallis feugiat, justo purus aliquam nisi, nec sodales est metus ac turpis. Pellentesque ultricies suscipit velit non hendrerit. Suspendisse aliquam eget leo laoreet interdum. Nulla fringilla nisi facilisis metus egestas, non ultricies neque suscipit. Vestibulum in diam pharetra, hendrerit nibh at, scelerisque orci. Sed vel est porttitor, rhoncus dui non, iaculis ante. Proin sit amet lacinia mi, vitae mattis neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla id tempor quam.</p>

app/views/core/index.html.erb
<h1>Home</h1>

<section>
	<h3>Membership</h3>

	<p>For our 2013/14 year we welcome 15 new members – David and Julia Aldous- Cook, Naomi Aruliah, Mansoureh de Brett, Thelma Drake, Andrew and Gillian Eperson, Geoff Gunton, Pam Hudson, Jean Hunt, Yvonne Jessop, Sue Muckle, Liz Swinton, Byron Theo and Barbara Verdie.</p>

	<p>The membership of the Club is currently 78, with 66 primarily playing Croquet and 12 primarily playing Bowls.</p>
</section>

<section>
	<h3>Club Sessions</h3>

	<p>There are Club sessions for Golf Croquet on Tuesday and Wednesday mornings, Thursday and Sunday afternoons and Wednesday evening. There is one session for Association Croquet each Sunday morning and two sessions for Bowls on Monday and Wednesday afternoons.</p>

	<p>Some members have very kindly agreed to try to attend some of the Golf Croquet Club sessions on a regular basis so that any member turning up has someone to play with. These are normally the Tuesday and Wednesday morning and Thursday afternoon sessions. If you arrive at a Club session and there is no one else there it is a good opportunity to set the hoops out and do some practice. This sort of practice can be very valuable in improving your skills.</p>

	<p>Please play on the full lawn when you can as it is much better practice. The half lawns should normally only be used when there are more than 8 members at a session.</p>
</section>

<section>
	<h3>Coaching</h3>

	<p>The Club now has 3 qualified Croquet coaches – Ian Cobbold for Golf and Neil Coote and Geoff Gunton for Association.</p>

	<p>Ian has already done some coaching sessions this year and will be offering some more dates shortly, giving initial priority to newer members. Neil and Geoff would be glad to hear from any members who would like to learn (more) about Association croquet.</p>

	<p>If any members would like coaching for Bowls please contact John Davies or Ben Bennett.</p>
</section>

<section>
	<h3>Public Coaching Course</h3>

	<p>We will again be running a Croquet course for members of the public which will take place on Tuesday and Thursday evenings between 6th and 22nd August. Last year’s course produced 4 new members for the Club.</p>

	<p>As we did last year, if there are spare spaces on the course these will be offered to existing members.</p>
</section>

<section>
	<h3>Social Events</h3>

	<p>Tea and cakes afternoons with Golf Croquet and Bowls. These Saturday afternoon sessions have proved very popular with members and the Committee is very grateful to Angeles Walford and her band of cake makers for putting them on. The next one is on Saturday 20th July starting at 2pm and the following one on Saturday, 14th September.</p>

	<p>Angeles is planning a lunchtime BBQ on Sunday 18th August. Those members with e-mail will have received separate notification of this. Those members not on e-mail will find a notice about the BBQ in the same envelope as this newsletter.</p>

	<p>Looking further ahead reserve the dates of  Saturday 26th October for our Quiz Night and Fish and Chip Supper and Sunday, 8th December for our Christmas Cracker.</p>

	<p>In May we held a very enjoyable Club dinner at Banstead DownsGolf Club which was attended by some 30 members and guests. We hope to hold a similar event next Spring and that more members will wish to attend.</p>
</section>

<section>
	<h3>Internal Competitions</h3>

	<p>Various internal competitions are underway for both Croquet and Bowls. The first one completed was the Golf Croquet Level Doubles which took place last Saturday. It was won by Ken Hughes and Mary Lane, with Ruth Williams and Peggy Gill as runners up. Both pairs won 3 of their 4 matches but Ken and Mary prevailed on number of hoops run (25 – 22).</p>
</section>

<section>
	<h3>Club Matches</h3>

	<p>So far this year we have played 3 Friendly Golf Croquet Matches against other clubs. We won the match against Purley Bury 7 – 3, with 5 games drawn when their time was up. We narrowly lost to Reigate Priory 4 - 6 and rather more comprehensively to Merton 1 – 8.</p>

	<p>We have entered the South East Croquet Federation’s Golf Croquet Handicap League for the first time this year and our first match is at home against Parsons Green on 19th July. Each Club entered in the league plays 4 matches during the season.</p>

	<p>The results of our league and other matches will be reported in the next Newsletter and posted on the noticeboard in the clubhouse.</p>
</section>

app/views/core/links.html.erb
<h1>Links to Croquet Sites</h1>

<article>
	<h3>The Croquet Association -</h3>
	<ul>
		<li><h5><a href="http://www.croquet.org.uk/">Croquet Association Home Page</a></h5></li>

		<li><h5><a href="http://www.croquet.org.uk/tournament">Croquet Association Events</a></h5></li>
	</ul>
</article>

<article>
	<h3>South East Croquet -</h3>
	<ul>
		<li><h5><a href="http://www.southeastcroquet.org.uk/">South East Croquet</a></h5></li>
	</ul>
</article>

<article>
	<h3>Croquet Academy -</h3>
	<ul>
		<li><h5><a href="http://www.thecroquetacademy.com/">Croquet Academy</a></h5></li>
	</ul>
</article>

<article>
	<h3>Croquet Equipment -</h3>
	<ul>
		<li><h5><a href="http://www.oxfordcroquet.com/equip/">Mallets, etc</a></h5></li>
		<li><h5><a href="http://www.bowlsdirect.com/contact.htm">Whites</a></h5></li>
	</ul>
</article>

<article>
	<h3>Croquet Glossary -</h3>
	<ul>
		<li><h5><a href="http://cornwall-croquet.org.uk/croquet_glossary.htm">Croquet Glossary</a></h5></li>
	</ul>
</article>

<article>
	<h3>Croquet Rules -</h3>
	<ul>
		<li><h5><a href="http://www.croquet.org.uk/association/laws/basic_aclaws.html">Association Rules</a></h5></li>
		<li><h5><a href="http://www.croquet.org.uk/?p=golf/laws/basic_gclaws.html">Golf Rules</a></h5></li>
	</ul>
</article>

app/views/core/news_letters.html.erb
<h1>News Letters</h1>

<article id="news_letters">
	<% @grouped.each do |year, newsletters| %>
        <section>
    		<h3><%= year %></h3>

            <% newsletters.each do |pdf| %>
                <p>
        			<h5><%= link_to pdf.title, pdf.pdf.to_s %></h5>
                </p>
            <% end %>
        </section>
	<% end %>
</article>

app/views/core/programme.html.erb
<h1><%= @title %></h1>

<article id="events">
	<% @events.each do |event| %>
        <%= render 'event', event: event %>
	<% end %>
</article>

<article id="past_events">
    <h2>Past Events - </h2>
    <% @past_events.each do |event| %>
        <%= render 'event', event: event %>
    <% end %>
</article>

<button id="toggle_events">Click here to show past events</button>

app/views/core/update_booking.html.erb
<h2>Success!</h2>
<p><%= @lawn.description %> has been succesfully booked for <%= @booking.date.to_formatted_s(:long) %> at <%= @booking.time.to_formatted_s(:time) %>.</p>
<%= link_to "Book another Lawn", book_a_lawn_path %>

app/views/core/what_you_need.html.erb
<h1>What You Need</h1>

<p>When you join the Club and start to learn how to play the game you do not need to be involved in any expense as far as equipment is concerned.</p>

<p>Initially you can borrow a club mallet and use it until you are sure that you like the game and until you know what sort of mallet you want to buy for your personal use. The only requirement to start with is that you should wear flat-soled shoes on the lawn to avoid damage.</p>

<p>When you start playing in matches it is suggested that you get "whites" to play in as this is the accepted norm for matches and tournament play.</p>

app/views/layouts/_footer.html.erb
<footer>
    <%= Time.now.year %> Cheam Croquet &amp; Bowls Club &copy; Ryan Harrison
</footer>

app/views/layouts/_header.html.erb
<header id="page_header" role="banner">
    <%= image_tag "cheam_croquet_logo_small.jpg", alt: "Logo" %>
	<h1>Cheam Croquet &amp; Bowls Club</h1>
    <h3>It's not just any Croquet and Bowls Club, it's the Cheam Croquet and Bowls Club.</h3>
</header>

app/views/layouts/_navigation.html.erb
<nav>
	<ul>
		<li><%= link_to 'Home', root_path  %></li>
		<li><%= link_to 'About the Club', about_the_club_path  %></li>
		<li><%= link_to 'How to Join', how_to_join_path  %></li>
		<li><%= link_to 'What You Need', what_you_need_path  %></li>
		<li><%= link_to Time.now.year.to_s + ' Programme', programme_path  %></li>
		<li><%= link_to 'News Letters', news_letters_path  %></li>
		<li><%= link_to 'Club Matters', club_matters_path  %></li>
		<li><%= link_to 'How to get There', how_to_get_there_path  %></li>
		<li><%= link_to 'Book a Lawn', book_a_lawn_path  %></li>
		<li><%= link_to 'Links', links_path  %></li>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title><%= title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="container">
    	<%= render 'layouts/header' %>
    	<%= render 'layouts/navigation' %>

    	<%= yield %>

    	<%= render 'layouts/footer' %>
    </div>
</body>
</html>